### PR TITLE
UI Tools for Manually Adjusting Background Map Scaling/Positioning

### PR DESCRIPTION
**Pull request by alexjohnson505**
Note: Does NOT currently save the changes. We have to manually save the parameters to options.maps....

### CODE REVIEW

**Comment by alexjohnson505** [comment]
Please look at and merge https://github.com/spacial-player-data-visualization/g-player-visualization/pull/28 before this PR.

**Comment by alexjohnson505** [comment]
screen shot 2015-04-05 at 3 14 51 pm

**Comment by tomxhu** [comment]
:+1:

**Comment by tomxhu** [comment]
:horse:

**Comment by alexwjacks** [comment]
+1.

**Pull request merged**
