### PR TITLE
Improve Data Representation

### PR DESCRIPTION
**Pull request by alexjohnson505**
Players position paths, and event locations should now be better represented
screen shot 2015-04-02 at 10 41 03 pm

### CODE REVIEW

**Comment by alexjohnson505** [comment]
Merge https://github.com/spacial-player-data-visualization/g-player-visualization/pull/26 before analyzing this branch, as it contains Pull 26's changes.

**Comment by pragsanshi** [comment]
This looks amazing!! We can follow up with the clients about what information they actually want displayed (if not all) but for demo purposes this is great. Looks like the layers still need work but we can push that elsewhere if needed. +1

**Comment by alexwjacks** [comment]
+1.

**Comment by tomxhu** [comment]
:cool:

**Pull request merged**
