### PR TITLE
Admin GUI and File Structure

### PR DESCRIPTION
**Pull request by alexjohnson505**
Ok, ALL sorts of fun new changes in this PR:

1.) **No more settings.js file!!!!**

2.) Editing maps via the GUI
screen shot 2015-04-16 at 4 12 12 pm

3.) Button for previewing player data
screen shot 2015-04-16 at 4 12 39 pm

4.) Wired up admin GUI
screen shot 2015-04-16 at 4 12 53 pm

### CODE REVIEW

**Comment by pragsanshi** [comment]
UI for editing maps and kep mappings is awesome, nice to have it all in one place in the side nav bar! 

:+1:

**Comment by tomxhu** [comment]
good to me

**Comment by alexjohnson505** [comment]
I want to get the settings entered into the production database before we merge this branch.

**Comment by pragsanshi** [comment]
Settings are into database! Can be merged.

**Comment by alexjohnson505** [comment]
Updated description above ^

**Comment by alexwjacks** [comment]
This is fantastic, +1

**Pull request merged**
