### PR TITLE
Combine api and frontend

### PR DESCRIPTION
**Pull request by tomxhu**
restructuring our app to have one app for front and backend

I deployed it onto heroku for now, can we make sure I didn't break anything?

http://g-player.herokuapp.com/

### CODE REVIEW

**Comment by alexwjacks** [comment]
This seems solid to me. +1

**Comment by alexjohnson505** [comment]
Sweet! Thanks for doing this. Want to keep the API's README.md file? I figure it has important info for how to run the API locally.

**Comment by tomxhu** [comment]
Eh not really, I just stole the Readme from wtv the heroku default node app was. the only thing to run this locally would be to have a running instance of mongo running

**Comment by alexwjacks** [comment]
I'm taking alex's comment as an implicit +1 and merging this.

**Pull request merged**
