### PR TITLE
Json upload

### PR DESCRIPTION
**Pull request by iambroadband**
Now shows position data as points when using the timeline

### CODE REVIEW

**Comment by alexjohnson505** [comment]
**Cool!** If you didn't want to store `moment.js` within the repo, you could use an external CDN:
`https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.11.2/moment.min.js`

**Comment by iambroadband** [comment]
I'll look into it. I am working on this .json thing. Shouldn't be too hard.
Just need to accept .json in addition to or in place of .csv

**Comment by alexjohnson505** [comment]
That's good to hear. Is the mod able to export JSON, or is someone converting the .csvs?

The uploading library [papaparse](http://papaparse.com/) that you're using *should* support uploading JSON files.

**Comment by iBroadband** [comment]
We are taking on a DARPA contract using json formatted data. Json is also
just an  easier way to support more detailed data.

**Comment by alexjohnson505** [comment]
Oh, that's so cool! Most definitely - especially since the program internally represents data as JSON, it's the way to go.

**Pull request merged**
