### PR TITLE
Add UI Modals for Viewing Menu and RAW Player Data

### PR DESCRIPTION
**Pull request by alexjohnson505**
screen shot 2015-04-06 at 7 20 24 pm

### CODE REVIEW

**Comment by alexjohnson505** [comment]
Also, fixes heatmap!

**Comment by pragsanshi** [comment]
+1: Love this design, I think it is important to separate uploading data from manipulating data

**Comment by alexjohnson505** [comment]
Data should new be getting HTML-itized before it's added to the modal.

screen shot 2015-04-06 at 8 56 41 pm

**Comment by alexwjacks** [comment]
+1.

**Pull request merged**
