### PR TITLE
Click the '+' button to add a single user to the map.

### PR DESCRIPTION
**Pull request by alexjohnson505**

### CODE REVIEW

**Comment by alexjohnson505** [comment]
screen shot 2015-04-06 at 7 19 49 pm

**Comment by pragsanshi** [comment]
screen shot 2015-04-06 at 8 22 08 pm

Looks like some of the preview data goes past the modal area. Maybe instead of showing all the rows, we can do the preview of the top 100 or so?

**Comment by alexjohnson505** [comment]
The main functionality of this modal is to look at specific entries in that data. For example: "Where is that odd point that's not on the map?". What do you think? Should I put in a line break? That would make it longer... but might not be a problem.

**Comment by pragsanshi** [comment]
Just for aesthetics, a line break might be just what we need. I think it will wrap onto the second line and remain just two lines like before (so hopefully, won't be longer). Check it out and we'll make a decision? Just so the clients don't think this is a bug haha

**Comment by alexwjacks** [comment]
Agreed on the line break, at least worth trying it. Either way, +1.

**Pull request merged**
